#pragma once

class Leaf;
class TypeNode;
class FormalParamsNode;
class ActualParamsNode;
class CallNode;
class BinaryNode;
class UnaryNode;
class AssignmentNode;
class ReturnNode;
class BlockNode;
class ProgramNode;
class FunctionNode;
class ElseNode;
class ElifNode;
class IfNode;
class WhileNode;
class ForNode;
class ListNode;
